### ISSUE TITLE
URL to play with kubernetes is bad

### ISSUE THREAD

**Issue by sudhanshug16** [ajeetraina/kubernetes101#4]
Hey,
In the README, the first step is this:
> Open https://labs.play-with-kubernetes.com on your browser

But if you open that, nothing loads. I am assuming the link is down. Is there an alternative to this step? Or an alternative link?
Also, https://labs.play-with-k8s.com/ doesn't work either

**Comment by Rahul-RB** [comment]
https://labs.play-with-k8s.com/ seems to working fine now.

**Comment by drahamim** [comment]
@Rahul-RB  The README has the wrong URL.
 https://labs.play-with-kubernetes.com is still in the readme which doesn't work.

**Comment by Rahul-RB** [comment]
Yes I know. There's already an open PR for that. (#1 )

**Comment by ajeetraina** [comment]
Fixed the URL.
