### ISSUE TITLE
Will there be any update from Day 6 to the end?

### ISSUE THREAD

**Issue by orange888** [ajeetraina/kubernetes101#5]
Will there be any update from Day 6 to the end?

Day-6: Kubernetes & Networking
Day-7: Kubernetes & Storage
Day-8: Kubernetes on Raspberry Pi 3
Day-9: Kubernetes & CI-CD

Thanks.

**Comment by ajeetraina** [comment]
Hello @orange888 I have added till Day-12 and still counting.
Also, please visit kubelabs.collabnix.com
