### ISSUE TITLE
There is pic that is not loaded in the beginners getting started section.

### ISSUE THREAD

**Issue by mkarjun** [ajeetraina/kubernetes101#7]
Hi! @ajeetraina 
https://github.com/ajeetraina/kubernetes101/blob/master/concept/day-1/getting-started.adoc#create-a-pod
![Screenshot 2022-11-30 120624](https://user-images.githubusercontent.com/23435593/204725256-5c82a53b-9970-42a0-a1df-384961d90958.png)

**Comment by ajeetsraina** [comment]
Suggest you to visit https://kubelabs.collabnix.com instead.

**Comment by mkarjun** [comment]
> Suggest you to visit https://kubelabs.collabnix.com instead.

Thanks @ajeetsraina
